apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: benthos-consumer
  namespace: rabbitmq
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    name: benthos-consumer
    kind: Deployment
  pollingInterval: 30
  cooldownPeriod: 10
  minReplicaCount: 1
  maxReplicaCount: 6
  triggers:
    - type: rabbitmq
      metadata:
        protocol: auto
        queueName: "q1"
        mode: QueueLength
        value: "10000"
        host: amqp://xavki:password@xavki-rabbitmq.rabbitmq.svc.cluster.local:5672/
