apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: ext-q1
  namespace: rabbitmq2
spec:
  name: q1
  vhost: vhost2
  type: quorum
  autoDelete: false
  durable: true
  rabbitmqClusterReference:
    connectionSecret:
      name: external-rabbitmq
