apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nfs-exporter
  namespace: nfs
spec:
  releaseName: nfs-exporter
  chart:
    name: nfs-subdir-external-provisioner
    version: 4.0.12
    repository: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
  values:
    nfs:
      server: 192.168.12.20
      path: /srv/rabbitmq/

