# Secrets de l'utilisateur
---
apiVersion: v1
kind: Secret
metadata:
  name: xavki-user
  namespace: rabbitmq
type: Opaque
stringData: # à encoder Data:
  username: xavki
  password: password

# Création du user
---
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: xavki
  namespace: rabbitmq
spec:
  tags:
  - administrator
  #- management
  rabbitmqClusterReference:
    name: xavki-rabbitmq
  importCredentialsSecret:
    name: xavki-user

# Affectation des permissions
---
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: xavki-permissions
  namespace: rabbitmq
spec:
  vhost: "vhost1"
  user: "xavki"
  permissions:
    write: ".*"
    configure: ".*"
    read: ".*"
  rabbitmqClusterReference:
    name: xavki-rabbitmq
